//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManOCL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManOCL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of arguments supplied is not equal to actual amount of arguments for kernel {0}.
        /// </summary>
        internal static string Amount_of_arguments_supplied_is_not_equal_to_actual_amount_of_arguments_for_kernel {
            get {
                return ResourceManager.GetString("Amount_of_arguments_supplied_is_not_equal_to_actual_amount_of_arguments_for_kerne" +
                        "l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array out of bounds.
        /// </summary>
        internal static string Array_out_of_bounds {
            get {
                return ResourceManager.GetString("Array_out_of_bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer out of bounds.
        /// </summary>
        internal static string Buffer_out_of_bounds {
            get {
                return ResourceManager.GetString("Buffer_out_of_bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceBufferStream.SetLength method can&apos;t change DeviceBuffer size because it is a fixed size object.
        /// </summary>
        internal static string DeviceBufferStream_SetLength_method_can_t_change_DeviceBuffer_size_because_it_is_a_fixed_size_object {
            get {
                return ResourceManager.GetString("DeviceBufferStream_SetLength_method_can_t_change_DeviceBuffer_size_because_it_is_" +
                        "a_fixed_size_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create single kernel because there are multiple kernels found in source code.
        /// </summary>
        internal static string Failed_to_create_single_kernel_because_there_are_multiple_kernels_found_in_source_code {
            get {
                return ResourceManager.GetString("Failed_to_create_single_kernel_because_there_are_multiple_kernels_found_in_source" +
                        "_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SeekOrigin.
        /// </summary>
        internal static string Invalid_SeekOrigin {
            get {
                return ResourceManager.GetString("Invalid_SeekOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalWorkSize and GlobalWorkSize dimensions do not agree.
        /// </summary>
        internal static string LocalWorkSize_and_GlobalWorkSize_dimensions_do_not_agree {
            get {
                return ResourceManager.GetString("LocalWorkSize_and_GlobalWorkSize_dimensions_do_not_agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory object was already pinned.
        /// </summary>
        internal static string Memory_object_was_already_pinned {
            get {
                return ResourceManager.GetString("Memory_object_was_already_pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory object was not pinned.
        /// </summary>
        internal static string Memory_object_was_not_pinned {
            get {
                return ResourceManager.GetString("Memory_object_was_not_pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple OpenCL devices found.
        /// </summary>
        internal static string Multiple_OpenCL_devices_found {
            get {
                return ResourceManager.GetString("Multiple_OpenCL_devices_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments specified for kernel {0}.
        /// </summary>
        internal static string No_arguments_specified_for_kernel {
            get {
                return ResourceManager.GetString("No_arguments_specified_for_kernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No kernels found.
        /// </summary>
        internal static string No_kernels_found {
            get {
                return ResourceManager.GetString("No_kernels_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No OpenCL devices found.
        /// </summary>
        internal static string No_OpenCL_devices_found {
            get {
                return ResourceManager.GetString("No_OpenCL_devices_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenCL error occured, ErrorCode = &apos;{0}&apos;, additional info:
        ///{1}.
        /// </summary>
        internal static string OpenCL_error_occured_ErrorCode_additional_info {
            get {
                return ResourceManager.GetString("OpenCL_error_occured_ErrorCode_additional_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program and CommandQueue Context properties do not match.
        /// </summary>
        internal static string Program_and_CommandQueue_Context_properties_do_not_match {
            get {
                return ResourceManager.GetString("Program_and_CommandQueue_Context_properties_do_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program failed to build, ErrorCode = {0}
        ///BuildLog:
        ///{1}
        ///Additional info:
        ///{2}.
        /// </summary>
        internal static string Program_failed_to_build_ErrorCode_BuildLog_Additional_info {
            get {
                return ResourceManager.GetString("Program_failed_to_build_ErrorCode_BuildLog_Additional_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream out of bounds.
        /// </summary>
        internal static string Stream_out_of_bounds {
            get {
                return ResourceManager.GetString("Stream_out_of_bounds", resourceCulture);
            }
        }
    }
}
